# Based on https://github.com/galaxy119/EXILED/blob/master/.github/workflows/main.yml

name: Build

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nuget
      uses: iRebbok/setup-nuget@master

    - name: Restore Packages
      run: nuget restore AmongSCP.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Download references
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/build_deps/References.zip'
        file-name: 'References.zip'

    - uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://github.com/SCPStats/Plugin/releases/download/1.5.5/SCPStats.dll'
        file-name: 'SCPStats.dll'

    - name: Download 7zip
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/7za.exe'
        file-name: '7zip.exe'

    - name: Extract Refs
      run: ./7zip.exe e References.zip -oAmongSCP/lib/ -r -y

    - run: move SCPStats.dll AmongSCP/lib/SCPStats.dll

    - name: Build
      run: msbuild AmongSCP.sln -p:Configuration=release

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Plugin DLL
        path: AmongSCP/bin/Release/AmongSCP*.dll
